server:
  port: 80
  servlet:
    session:
      tracking-modes: cookie
spring:
  application:
    name: react_crud
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/test
    username: root
    password: 123
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: pack.dto.**